name: Uganda Data ScheduledFetch

on: 
  schedule:
    - cron: "30 2 * * SUN-SAT"
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
        
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
                
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run file to fetch data and save to csv file
      run: python eda_files/eda.py
      continue-on-error: true
    
    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        commit_message: Updated source csv file
